/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChapterMeta = IDL.Record({
  'chapterNumber' : IDL.Nat,
  'sanskritName' : IDL.Text,
  'totalSlokas' : IDL.Nat,
  'summary' : IDL.Text,
  'englishName' : IDL.Text,
});
export const MultiLangText = IDL.Record({
  'hindi' : IDL.Text,
  'telugu' : IDL.Text,
  'sanskrit' : IDL.Text,
  'english' : IDL.Text,
});
export const Sloka = IDL.Record({
  'chapterNumber' : IDL.Nat,
  'meanings' : MultiLangText,
  'sanskritText' : IDL.Text,
  'explanation' : IDL.Text,
  'transliteration' : IDL.Text,
  'slokaNumber' : IDL.Nat,
});
export const PagedResult = IDL.Record({
  'page' : IDL.Nat,
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(Sloka),
});

export const idlService = IDL.Service({
  'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(ChapterMeta)], ['query']),
  'getChapterSlokas' : IDL.Func([IDL.Nat], [IDL.Vec(Sloka)], ['query']),
  'getChapters' : IDL.Func([], [IDL.Vec(ChapterMeta)], ['query']),
  'getDailySloka' : IDL.Func([], [IDL.Opt(Sloka)], ['query']),
  'getSloka' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Sloka)], ['query']),
  'searchSlokas' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [PagedResult],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChapterMeta = IDL.Record({
    'chapterNumber' : IDL.Nat,
    'sanskritName' : IDL.Text,
    'totalSlokas' : IDL.Nat,
    'summary' : IDL.Text,
    'englishName' : IDL.Text,
  });
  const MultiLangText = IDL.Record({
    'hindi' : IDL.Text,
    'telugu' : IDL.Text,
    'sanskrit' : IDL.Text,
    'english' : IDL.Text,
  });
  const Sloka = IDL.Record({
    'chapterNumber' : IDL.Nat,
    'meanings' : MultiLangText,
    'sanskritText' : IDL.Text,
    'explanation' : IDL.Text,
    'transliteration' : IDL.Text,
    'slokaNumber' : IDL.Nat,
  });
  const PagedResult = IDL.Record({
    'page' : IDL.Nat,
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(Sloka),
  });
  
  return IDL.Service({
    'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(ChapterMeta)], ['query']),
    'getChapterSlokas' : IDL.Func([IDL.Nat], [IDL.Vec(Sloka)], ['query']),
    'getChapters' : IDL.Func([], [IDL.Vec(ChapterMeta)], ['query']),
    'getDailySloka' : IDL.Func([], [IDL.Opt(Sloka)], ['query']),
    'getSloka' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Sloka)], ['query']),
    'searchSlokas' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [PagedResult],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };