/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChapterMeta {
  'chapterNumber' : bigint,
  'sanskritName' : string,
  'totalSlokas' : bigint,
  'summary' : string,
  'englishName' : string,
}
export interface MultiLangText {
  'hindi' : string,
  'telugu' : string,
  'sanskrit' : string,
  'english' : string,
}
export interface PagedResult {
  'page' : bigint,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'items' : Array<Sloka>,
}
export interface Sloka {
  'chapterNumber' : bigint,
  'meanings' : MultiLangText,
  'sanskritText' : string,
  'explanation' : string,
  'transliteration' : string,
  'slokaNumber' : bigint,
}
export interface _SERVICE {
  'getChapter' : ActorMethod<[bigint], [] | [ChapterMeta]>,
  'getChapterSlokas' : ActorMethod<[bigint], Array<Sloka>>,
  'getChapters' : ActorMethod<[], Array<ChapterMeta>>,
  'getDailySloka' : ActorMethod<[], [] | [Sloka]>,
  'getSloka' : ActorMethod<[bigint, bigint], [] | [Sloka]>,
  'searchSlokas' : ActorMethod<[string, bigint, bigint], PagedResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];